# 第七次培训笔记

## 1.作业有关的知识点整理

### 1.类的继承

`object`基类

`type` 元类

- 在python中，一切都是对象，类也是对象，所有一个类(class)必须有一个类型(type)

`property` 属性描述符   把方法变成属性



## 2.其他面向对象的知识补充

魔术方法

- __init__ 是在创建对象的时候自动调用，对创建的对象进行初始化设置的
- __new__ 是实力化对象的时候自动调用的
- __new__ 方法在__init__方法之前调用，先实例了对象，在给实例初始化属性

```
class Mycalss(object):
    def __init__(self, name):
        print("这个是init方法")
        self.name = name

    # 重写 __new__方法
    def __new__(cls, *args, **kwargs):
        print("这个是new方法")
        # 创建对象是python底层帮我实现，重写之后需要返回父类的创建对象的方法，不然实例不出对象
        return object.__new__(cls)


m = Mycalss("DaBai")  # 先进入new方法 在执行init方法
```

__init__初始化

__getattribute__ 访问属性

| __getattr__(self, name)      | 定义当用户试图获取一个不存在的属性时的行为 |
| ---------------------------- | ------------------------------------------ |
| __getattribute__(self, name) | 定义当该类的属性被访问时的行为             |



## 3.异常处理

### 1.异常 VS 错误

#### 异常

- 产生没有预料到的结果

#### 错误

- 语法错误
- 对需求的理解错误

### 2.捕获异常

#### 1.`Traceback`

```
def a():
    b()
    
def b():
    c()
   
def c():
    d()
   
def d():
    return 1/0

a()
```

#### 2.`try ... except`

##### 1.常见异常类型

| 异常名称                  | 描述                                               |
| ------------------------- | -------------------------------------------------- |
| BaseException             | 所有异常的基类                                     |
| SystemExit                | 解释器请求退出                                     |
| KeyboardInterrupt         | 用户中断执行(通常是输入^C)                         |
| Exception                 | 常规错误的基类                                     |
| StopIteration             | 迭代器没有更多的值                                 |
| GeneratorExit             | 生成器(generator)发生异常来通知退出                |
| StandardError             | 所有的内建标准异常的基类                           |
| ArithmeticError           | 所有数值计算错误的基类                             |
| FloatingPointError        | 浮点计算错误                                       |
| OverflowError             | 数值运算超出最大限制                               |
| ZeroDivisionError         | 除(或取模)零 (所有数据类型)                        |
| AssertionError            | 断言语句失败                                       |
| AttributeError            | 对象没有这个属性                                   |
| EOFError                  | 没有内建输入,到达EOF 标记                          |
| EnvironmentError          | 操作系统错误的基类                                 |
| IOError                   | 输入/输出操作失败                                  |
| OSError                   | 操作系统错误                                       |
| WindowsError              | 系统调用失败                                       |
| ImportError               | 导入模块/对象失败                                  |
| LookupError               | 无效数据查询的基类                                 |
| IndexError                | 序列中没有此索引(index)                            |
| KeyError                  | 映射中没有这个键                                   |
| MemoryError               | 内存溢出错误(对于Python 解释器不是致命的)          |
| NameError                 | 未声明/初始化对象 (没有属性)                       |
| UnboundLocalError         | 访问未初始化的本地变量                             |
| ReferenceError            | 弱引用(Weak reference)试图访问已经垃圾回收了的对象 |
| RuntimeError              | 一般的运行时错误                                   |
| NotImplementedError       | 尚未实现的方法                                     |
| SyntaxError               | Python 语法错误                                    |
| IndentationError          | 缩进错误                                           |
| TabError                  | Tab 和空格混用                                     |
| SystemError               | 一般的解释器系统错误                               |
| TypeError                 | 对类型无效的操作                                   |
| ValueError                | 传入无效的参数                                     |
| UnicodeError              | Unicode 相关的错误                                 |
| UnicodeDecodeError        | Unicode 解码时的错误                               |
| UnicodeEncodeError        | Unicode 编码时错误                                 |
| UnicodeTranslateError     | Unicode 转换时错误                                 |
| Warning                   | 警告的基类                                         |
| DeprecationWarning        | 关于被弃用的特征的警告                             |
| FutureWarning             | 关于构造将来语义会有改变的警告                     |
| OverflowWarning           | 旧的关于自动提升为长整型(long)的警告               |
| PendingDeprecationWarning | 关于特性将会被废弃的警告                           |
| RuntimeWarning            | 可疑的运行时行为(runtime behavior)的警告           |
| SyntaxWarning             | 可疑的语法的警告                                   |
| UserWarning               | 用户代码生成的警告                                 |

##### 2.不知道异常类型

```
try:
    1/0
except Exception as e:
    print(e)
```

##### 3.已知异常类型

```
def f1():
    1/0

def f2():
    list1 = []
    list1[1]    
    f1()
    
def f3():
    f2()

try:
    f3()
except (ZeroDivisionError,Exception) as e:  #从前到后捕获
    print(e)  
```

#### 3.主动抛出异常(理解,背下来)

```
class UserInputError(Exception):
    def __init__(self, ErrorInfo):
        super().__init__(self, ErrorInfo)  #父类初始化
        self.errorinfo = ErrorInfo
    def __str__(self):
        return self.errorinfo

userinput = 'a'

try:
    if (not userinput.isdigit()):
        raise UserInputError('用户输入错误')
except UserInputError as ue:
    print(ue)
finally:    #无论是否处理异常,都要执行
    del userinput
```

#### 4.异常美化(第三方库 `pretty_errors`)

#### 5.文件处理时的异常(使用`with`)

```
file1 = open('a.txt', encoding='utf8')
try:
    data = file1.read()
finally:
    file1.close()

with open('a.txt', encoding='utf8') as file2:
    data = file2.read()
```

